version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:${PGVERSION}-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDB:-postgres}
    ports:
      - "${PGEXPOSE:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  db:


networks:
  backend_network:
    external: true
