version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:${PG_VERSION}-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOSTNAME=${PG_HOSTNAME}
      - POSTGRES_DATABASE=${PG_DATABASE}
    ports:
      - "${PG_EXPOSE}:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
